### ISSUE TITLE
latesst PHP 8.2.15

### ISSUE THREAD

**Issue by degoya** [dwchiang/nginx-php-fpm#21]
i've seen that you haven't updated to the latest versions of PHP yet, do you still update them or not?

**Comment by dwchiang** [comment]
We are working on it :)

**Comment by dwchiang** [comment]
At the mean time, do you mind to share your use cases with us? That would be the great support for us to continue this project :)

👉 [Let us know you are using it](https://forms.gle/yvEeR2D1voc7sJbaA)

**Comment by dwchiang** [comment]
@degoya we just added latest PHP 8.2.15 in the repo, enjoy :)
