### ISSUE TITLE
Assumption of supervisor in the readme.

### ISSUE THREAD

**Issue by gorkomikus** [dwchiang/nginx-php-fpm#23]
Hi,

I am not a expert in php and Supervisor and just want to be sure to understand the below documentation correctly.

We are adding an additional service in Supervisor by copying our config file, named supervisor.config to the /etc/supervisor/conf.d folder. 

In the docs we read the below:

-  _/etc/supervisor/conf.d/*.conf: If you have some other extra supervisor conf files, place here._

See https://github.com/dwchiang/nginx-php-fpm/blob/master/README.md#part-1-base-image. 

Is it true that with adding our config file the processes nginx and php-fpm are still managed by supervisor? In other words adding our config file is a merge additional configuration?

**Comment by fmiqbal** [comment]
From what i can see from the config file below (specifically for bullseye), I can tell it should be,

https://github.com/dwchiang/nginx-php-fpm/blob/master/Dockerfiles/bullseye/conf/supervisord.conf

it has nginx and php-fpm already and it will **include** your supervisor conf from the `conf.d` folder

https://github.com/dwchiang/nginx-php-fpm/blob/70873195f7fa024b7d2779dc7f5695616de2279f/Dockerfiles/bullseye/conf/supervisord.conf#L28-L29

Check out your image flavour Dockerfile and conf folder for more info, 
and you can always try running the image yourself and try :)

**Comment by gorkomikus** [comment]
Thanks for the reaction. It indeed is. If ran the container and looked in the supervisord log file (/tmp/supervisord.log) and can confrim they are running. Thanks for the help!
