### ISSUE TITLE
Security update

### ISSUE THREAD

**Issue by lutifyme** [dwchiang/nginx-php-fpm#7]
Hello,

PHP versions 7.3.x up to and including 7.3.31, 7.4.x below 7.4.25 and 8.0.x below 8.0.12 are vulnerable to privilege escalation vulnerability. The vulnerability allows the root FPM process to read/write at arbitrary locations using pointers located in the SHM (Shared memory), leading to a privilege escalation from www-data to root. Vulnerability applies only to PHP-FPM.

See here: https://bugs.php.net/bug.php?id=81026

It would be nice if the updated and patched versions could be included.

**Comment by dwchiang** [comment]
Thank you for the heads-up.

**Comment by dwchiang** [comment]
Uploading images of FPM 7.3.32, 7.4.25, 8.0.12 in both Docker Hub, and AWS ECR Public. 

I will update Dockerfiles in this repo later today.

**Comment by lutifyme** [comment]
Thanks for your prompt response
