### ISSUE TITLE
Error when trying to use 8.1.0RC5

### ISSUE THREAD

**Issue by code-a-cola** [dwchiang/nginx-php-fpm#9]
ARG VERSION=8.1.0RC5-fpm-buster-nginx-1.21.1
FROM dwchiang/nginx-php-fpm:${VERSION}

The error I'm receiving is

ERROR: Service 'dockeraws' failed to build: manifest for dwchiang/nginx-php-fpm:8.1.0RC5-fpm-buster-nginx-1.21.1 not found: manifest unknown: manifest unknow

Also are their any images available that support he lastest version of PHP 8.1.4 ?

**Comment by dwchiang** [comment]
Sorry for the late reply. I finally managed to combine multiple versions of PHP x nginx x OS last weekend, and the good news is... yes! Now it comes with latest PHP 8.1.7 and 8.2 alpha :) 

Please give it a try, and let me know if everything works.
